// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHistory() {
  return window['go']['main']['Chat']['GetHistory']();
}

export function SendMessage(arg1) {
  return window['go']['main']['Chat']['SendMessage'](arg1);
}
